### ISSUE TITLE
Transformer Example Error

### ISSUE THREAD

**Issue by mschuttt** [daerion/octomore#1]
In the createTransformer([https://github.com/daerion/octomore#createtransformer-api](url)) documentation example there is an error:

```
const applyTransform = createTransformer({
  id: true,
  brandName: 'brand_name',
  fullName: ({ brand_name, aged_years }) => `${brand_name} (${aged_years} years)`,
  caskTypes: { src: 'casks.types', transform: (str) => str.split(', ') },
  age: { transform: (str) => parseInt(str, 10) },
  keywords: { transform: (str) => str.toUpperCase(), iterate: true, max: 3 }
})
```

The field `fullName` should be `({ brand_name, age })...` instead of `({ brand_name, aged_years })..`, since the property is called `age` and not `aged_years`

**Comment by msmesnik** [comment]
You're absolutely right, thanks for bringing this to my attention. Updated the README just now :)
